export const CoreErrorCode = Object.freeze({
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  PATH_OUTSIDE_WORKSPACE: "PATH_OUTSIDE_WORKSPACE",
  SENSITIVE_PATH: "SENSITIVE_PATH",
  SYMBOLIC_LINK: "SYMBOLIC_LINK",
  PATH_NOT_DIRECTORY: "PATH_NOT_DIRECTORY",
  PATH_NOT_FILE: "PATH_NOT_FILE",
  PATH_NOT_FOUND: "PATH_NOT_FOUND",
  DIRECTORY_NOT_EMPTY: "DIRECTORY_NOT_EMPTY",
  OPERATION_LIMIT_EXCEEDED: "OPERATION_LIMIT_EXCEEDED",
  ARTIFACT_SOURCE_NOT_ALLOWED: "ARTIFACT_SOURCE_NOT_ALLOWED",
  ARTIFACT_DOWNLOAD_FAILED: "ARTIFACT_DOWNLOAD_FAILED",
  ARTIFACT_INVALID: "ARTIFACT_INVALID",
  ARTIFACT_TYPE_NOT_ALLOWED: "ARTIFACT_TYPE_NOT_ALLOWED",
  ARTIFACT_EXPORT_EXPIRED: "ARTIFACT_EXPORT_EXPIRED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_CHANGED: "FILE_CHANGED",
  FILE_ALREADY_EXISTS: "FILE_ALREADY_EXISTS",
  BINARY_FILE: "BINARY_FILE",
  PATCH_INVALID: "PATCH_INVALID",
  PATCH_UNSUPPORTED: "PATCH_UNSUPPORTED",
  PATCH_CONTEXT_MISMATCH: "PATCH_CONTEXT_MISMATCH",
  TOOL_DISABLED: "TOOL_DISABLED",
  APPROVAL_DENIED: "APPROVAL_DENIED",
  COMMAND_NOT_ALLOWED: "COMMAND_NOT_ALLOWED",
  COMMAND_TIMEOUT: "COMMAND_TIMEOUT",
  PROCESS_FAILED: "PROCESS_FAILED",
  CHECKPOINT_NOT_FOUND: "CHECKPOINT_NOT_FOUND",
  CHECKPOINT_INVALID: "CHECKPOINT_INVALID",
  CHECKPOINT_LIMIT_EXCEEDED: "CHECKPOINT_LIMIT_EXCEEDED",
  CHECKPOINT_CONFLICT: "CHECKPOINT_CONFLICT",
  ROLLBACK_FAILED: "ROLLBACK_FAILED",
  IO_ERROR: "IO_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR"
});

export class CoreError extends Error {
  constructor(code, message, options = {}) {
    super(message, options);
    this.name = "CoreError";
    this.code = code;
    this.details = options.details || {};
  }
}

export function coreError(code, message, details = {}) {
  return new CoreError(code, message, { details });
}

export function normalizeCoreError(error, fallbackCode = CoreErrorCode.INTERNAL_ERROR) {
  if (error instanceof CoreError) return error;
  const message = error instanceof Error ? error.message : String(error);
  return new CoreError(fallbackCode, message, { cause: error });
}
